### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by templeblock** [mvitez/thnets#13]
[memorydebug.zip](https://github.com/mvitez/thnets/files/759762/memorydebug.zip)
 used my memorydebug, there are some memory leak found!
but , i don't know how to fix it.help me!plz.

**Comment by mvitez** [comment]
What should I run to see the memory leak?

**Comment by templeblock** [comment]
ref:
https://github.com/bibhas2/Memd

**Comment by mvitez** [comment]
I see, but I am asking what command line I should run to see the leak.

**Comment by templeblock** [comment]
just run the program,when use THFreeNetwork to free the network, the memory no free.
Memd can help to find  the memory leak position.
sorry for my bad english.

**Comment by mvitez** [comment]
I've found there is a problem with some new networks that I haven't checked before for memory leaks (in the recently implemented layers Concat etc.). I am looking at it now. Just for information, thnets has its own memory leak research routine, just make it with "make MEMORYDEBUG=1".

**Comment by templeblock** [comment]
i've test in windows and ios environment, i try to fix it.
but the problem drive  me crazy.
wait for your solution

**Comment by mvitez** [comment]
The memory leak has been fixed.

**Comment by templeblock** [comment]
thanks
