### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by paramsen** [mvitez/thnets#19]
Hi, I wonder if there is a roadmap for this project? I see it's under frequent development, so I wonder where it's headed.

**Comment by mvitez** [comment]
Hi. I am currently working with FWDNXT, so I am driven by the company requirements. We are currently using thnets in our compiler. Basically the target is to support as many networks as possible on our hardware.

**Comment by paramsen** [comment]
@mvitez Alright, well thanks for developing this, I couldn't get anywhere with torch-android due to weird memory issues.
