### ISSUE TITLE
ask for some details about the model directory

### ISSUE THREAD

**Issue by canneltigrou** [mvitez/thnets#21]
Hi,
I would like to use your project in order to read a Torch model on an embedded system.
But I don't understand the two files that are required into the model directory.

I would like to use Openface (https://cmusatyalab.github.io/openface/) : they use a lua script to open the model, but I have only one file : the model named nn4.small2.v1.t7

concerning your two files : 
- model.net the network file saved in .t7 format. I suppose I have just to rename my file into "model.net"
- stat.t7 contains a table with a 'std' and 'mean' FloatTensor of dimension 3. I don't understand what is this file ?

thanks for any answer,

**Comment by mvitez** [comment]
Hi,

stat.t7 is used to put the input image into the right range. It basically just subtracts mean from the input and divides it by std; mean and std are specified for each color plane. If you don't provide that file, mean will be 0 and std 1, leaving your input as is.

Best regards,
Marko.

**Comment by canneltigrou** [comment]
thank you very much :-) 

Best regards,
