### ISSUE TITLE
Missing openface modules

### ISSUE THREAD

**Issue by canneltigrou** [mvitez/thnets#22]
Hi (again)

I would like to be sure. When I try to open the openface neural network, I have this error : 
>> Unknown module type nn.SpatialCrossMapLRN

In fact, I think you have "translated" the majority of the lua modules, but you don't have implemented those that Openface requires?  
>> for NAME in dpnn nn optim ; do luarocks install $NAME; done
(https://cmusatyalab.github.io/openface/setup/)

Is it really difficult to add these three modules? (I think it is, but I ask) If it isn't, could you explain how I could add them? there is a git repository associated but they are in lua. (for example dpnn: https://github.com/nicholas-leonard/dpnn)

Thank you very much for your amazing work,
Best regards,

**Comment by mvitez** [comment]
I confirm that SpatialCrossMapLRN has not been implemented.

it's not really that simple. You have to convert lua code into C using existing thnets primitives.

**Comment by canneltigrou** [comment]
That is what I thought :-( 
Thank you for your answer !
