### ISSUE TITLE
How can I know the t7 file format

### ISSUE THREAD

**Issue by tzupingkao** [mvitez/thnets#4]
I refer to this thnets project.

But I want to know how can I get or know the torch t7 file format, for example a pdf or web document.

Could you give me a direction?

Thank you very much.

**Comment by mvitez** [comment]
It's simply an image saved in torch with the function torch.save. It's 
meant mostly for debugging, you are not supposed to use it. The test 
software can load jpegs and pngs, that's it.

**Comment by tzupingkao** [comment]
Because I want to learn the t7 file format, 

do you have the t7 spec?

**Comment by mvitez** [comment]
> do you have the t7 spec?
> No, I don't believe it exists. I looked at the Torch code.

**Comment by tzupingkao** [comment]
Thank you for your reply

**Comment by jhjin** [comment]
@tzupingkao Though this is painful, you can infer the t7 spec by looking the t7 file saved in ASCII format, for example, in Torch, 

``` lua
torch.save('asdf.t7', model, 'ascii')
```

and in terminal,

``` bash
vim asdf.t7
```

**Comment by tzupingkao** [comment]
Thank you, jhjin
