### ISSUE TITLE
Segfaults happening

### ISSUE THREAD

**Issue by mdaiter** [mvitez/thnets#7]
Hey,
I'm getting segfaults in my repo (https://github.com/mdaiter/thnets) when attempting to load PNNet (https://github.com/mdaiter/thnets/tree/master/networks). For some reason, it seems as though the tensor sizes aren't matching up. I'm loading a grayscale image (my code should take care of loading the grayscale image as a single-channel) into my net interface, and the net seems to load fine. However, after the model.net and stat.t7 load, the program segfaults when running it with -m 0 or -m 3. With -m 3, it segfaults with creating the forward tensor. With -m 0, it segfaults when performing the TH_TensorAdd with SSE2.
Thoughts? Is there a better way to perform this loading? Can you load this net as well? The original net was posted here: https://github.com/vbalnt/pnnet but the actual net contains corrupted recursive functions (code 8) that cause read-in problems. My repo fixes that.
Thanks,
Matthew Daiter

**Comment by mdaiter** [comment]
Also, for some specs:
Running on CUDA 8.0 with cuDNN v5. Already modified all of the internals to use cuDNN v5

**Comment by mdaiter** [comment]
@mvitez I'm finding errors on the read-in for kW and kH that aren't involved with any of the changes that I had made. This usually happens in the SpatialConvolution step. I can send you the net in ASCII or binary form. Can you take a look?
Maybe this relates to how we have the neural nets shifting from a 4D tensor input to a 2D tensor output?

**Comment by mdaiter** [comment]
@mvitez started to narrow down this problem. It appears as though the nn.View module, when loaded, isn't recognised. When passed through the cuDNN conversion schema, it's later converted to a SpatialConvolution. Any specific way to convert the View to a cuDNN view and also guarantee it's recognised?

**Comment by mdaiter** [comment]
AND found out you shouldn't make the View stuff Spatial. Currently works. Sorry for the noise!

**Comment by mvitez** [comment]
Sorry that I didn't help you, but I was out of my office for a few days. Great that you found the problem, which pushes me to add an option for ThMakeSpatial.
