### ISSUE TITLE
demo model dead link

### ISSUE THREAD

**Issue by austingg** [mvitez/thnets#8]
sorry for disturb, but the link of demo model is dead.

**Comment by mvitez** [comment]
Thank you for the info. I've removed the dead links.

**Comment by austingg** [comment]
@mvitez  Is there demo model for test ?

**Comment by mvitez** [comment]
There are two demo links here: https://github.com/teradeep/demo-apps. The first one is still alive.

**Comment by austingg** [comment]
@mvitez  got it. thanks for you kind help
