### ISSUE TITLE
does thnets support branch network?

### ISSUE THREAD

**Issue by austingg** [mvitez/thnets#9]
does thnets support branch network or only linear feed forward structure?

**Comment by mvitez** [comment]
I have recently added Concat, for CPU only.

**Comment by austingg** [comment]
does Concat equal ConcatTable in torch nn? 
I have just test a residual network, and got an unknown type "nn.ConcatTable"

**Comment by mvitez** [comment]
No, it's this one:
https://github.com/torch/nn/blob/master/doc/containers.md#nn.Concat

**Comment by austingg** [comment]
@mvitez  thanks a lot for you rely. I will try branch network
